# Generated by Django 6.0.6 on 2026-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='portal_emai_email_0c2e53_idx',
            old_name='portal_emai_email_e5c1a0_idx',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
