# Generated by Django 6.0.6 on 2026-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_portal_emai_email_e5c1a0_idx_portal_emai_email_0c2e53_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizen_photos/'),
        ),
    ]
