"""
Django settings for tunga_portal project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a .env file in the project root (if one exists).
# This only affects local development — on Render, environment
# variables are set directly in the dashboard and this call is a no-op
# there since no .env file is deployed.
load_dotenv(BASE_DIR / '.env')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*u35x1%04wmt)-r3ko4(gt85oao8^a(16sj=&3d*l86az4s10^')
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.sites',

    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'portal',
    'offices',
    'office_dashboard',
    'admin_dashboard',
    'tungamap',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_FORMS = {
    'signup': 'portal.forms.CustomSocialSignupForm',
}
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_ADAPTER = 'portal.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'portal.adapters.SocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tunga_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_dashboard.context_processors.site_contact_info',
                'admin_dashboard.context_processors.is_super_admin',
                'admin_dashboard.context_processors.ticker_announcements',
                'admin_dashboard.context_processors.nav_offices',
                'admin_dashboard.context_processors.public_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'tunga_portal.wsgi.application'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'


if not DEBUG:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
else:
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# ---------------------------------------------------------------------------
# DigitalOcean Spaces (for later, when the site moves to DigitalOcean).
# Turn it on with the environment variable USE_SPACES=1 plus:
#   SPACES_BUCKET, SPACES_KEY, SPACES_SECRET,
#   SPACES_REGION (e.g. sgp1), SPACES_CDN_DOMAIN (optional)
# Needs: pip install "django-storages[s3]" boto3   (add both to requirements.txt)
# Uploaded files go to <bucket>/media (public) and backups to
# <bucket>/backups (private). Nothing here runs until USE_SPACES=1.
# ---------------------------------------------------------------------------
if os.environ.get('USE_SPACES') == '1':
    _spaces_region = os.environ.get('SPACES_REGION', 'sgp1')
    _spaces = {
        "bucket_name": os.environ.get('SPACES_BUCKET'),
        "access_key": os.environ.get('SPACES_KEY'),
        "secret_key": os.environ.get('SPACES_SECRET'),
        "region_name": _spaces_region,
        "endpoint_url": f"https://{_spaces_region}.digitaloceanspaces.com",
        "file_overwrite": False,
    }
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {**_spaces, "location": "media", "default_acl": "public-read",
                    "querystring_auth": False, "custom_domain": os.environ.get('SPACES_CDN_DOMAIN') or None},
    }
    STORAGES["backups"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {**_spaces, "location": "backups", "default_acl": "private", "querystring_auth": True},
    }

# Where backups are kept when there is no STORAGES["backups"] (a private
# folder the website never serves). See admin_dashboard/backup.py.
BACKUP_ROOT = os.environ.get('BACKUP_ROOT') or (BASE_DIR / 'private_backups')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'