# Generated by Django 6.0.6 on 2026-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_sitecontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Medical / Rescue', 'Medical / Rescue'), ('Police', 'Police'), ('Health', 'Health'), ('Fire', 'Fire'), ('General', 'General')], default='General', max_length=30)),
                ('carrier_label', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('extra_detail', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
