# Generated by Django 6.0.6 on 2026-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('navy', 'Navy'), ('teal', 'Teal'), ('orange', 'Orange'), ('purple', 'Purple'), ('gray', 'Gray')], default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='icon',
            field=models.CharField(choices=[('fa-truck-medical', 'Ambulance'), ('fa-user-shield', 'Shield'), ('fa-heart-pulse', 'Heartbeat'), ('fa-fire', 'Fire'), ('fa-hospital', 'Hospital'), ('fa-life-ring', 'Life Ring'), ('fa-shield-halved', 'Shield Halved'), ('fa-house-fire', 'House Fire'), ('fa-phone-volume', 'Phone Volume'), ('fa-phone', 'Phone')], default='fa-phone', max_length=30),
        ),
    ]
