# Generated by Django 6.0.6 on 2026-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_emergencycontact_color_emergencycontact_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
