# Generated by Django 6.0.6 on 2026-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_sitecontactinfo_hero_banner_sitecontactinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='show_social_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
    ]
