# Generated by Django 6.0.6 on 2026-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_sitecontactinfo_show_social_footer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontactinfo',
            old_name='show_social_footer',
            new_name='show_facebook_footer',
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='show_instagram_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='show_twitter_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='show_youtube_footer',
            field=models.BooleanField(default=True),
        ),
    ]
