# Generated by Django 6.0.6 on 2026-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_rename_show_social_footer_sitecontactinfo_show_facebook_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('app_password_encrypted', models.TextField(blank=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Provider Settings',
                'verbose_name_plural': 'Email Provider Settings',
            },
        ),
    ]
