# Generated by Django 6.0.6 on 2026-09-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_emailprovidersettings_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('fa-file-lines', 'Document / Permit'), ('fa-camera', 'Tourism / Culture'), ('fa-hand-holding-heart', 'Financial Assistance'), ('fa-briefcase', 'Jobs / Employment'), ('fa-id-card', 'ID / Cedula'), ('fa-phone-volume', 'Phone / Hotline'), ('fa-map-location-dot', 'Map / Location'), ('fa-building', 'Office / Government')], default='fa-file-lines', max_length=50)),
                ('url', models.CharField(help_text='A path on this site (e.g. /offices/) or a full https:// link.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
