# Generated by Django 6.0.6 on 2026-10-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_quicklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/officials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_intro', models.TextField(default='The Municipality of Tunga is committed to good governance, transparent leadership, and the continuous progress and well-being of our people.')),
                ('vision_text', models.TextField(default='Tunga is an innovative Smart City, becoming the institutional training center focused on peace and security instrumentalities of Region 8, and the home for empowered citizens, and progressive climate-resilient and sustained environment governed by transparent and accountable leaders')),
                ('mission_text', models.TextField(default='“Our mission at Tunga is to establish a pioneering Smart City that serves as the premier training center for peace and security instrumentalities in Region 8. We are dedicated to empowering our citizens and fostering a progressive, climate-resilient environment, all while ensuring governance that is transparent and accountable.”')),
                ('core_values', models.TextField(default='Integrity\nTransparency\nAccountability\nExcellence\nService to Others', help_text='One value per line.')),
                ('history_intro', models.TextField(default='The Municipality of Tunga was formerly a barrio of the Municipality of Barugo. Through Executive Order No. 266, signed by President Elpidio Quirino on September 26, 1949, Tunga was officially created as an independent municipality.\nSince its creation, Tunga has continued to develop while preserving its agricultural heritage, close-knit community, and local traditions.', help_text='One paragraph per line.')),
                ('history_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('barangays_intro', models.CharField(default='The municipality is composed of 8 barangays.', max_length=255)),
                ('glance_population_value', models.CharField(default='34,567+', max_length=50)),
                ('glance_population_label', models.CharField(default='Population (2025 PSA Estimate)', max_length=100)),
                ('glance_land_area_value', models.CharField(default='78.45 km²', max_length=50)),
                ('glance_land_area_label', models.CharField(default='Total Land Area', max_length=100)),
                ('glance_households_value', models.CharField(default='8,652+', max_length=50)),
                ('glance_households_label', models.CharField(default='Households', max_length=100)),
                ('glance_established_value', models.CharField(default='Established', max_length=50)),
                ('glance_established_label', models.CharField(default='September 26, 1949 (E.O. No. 266)', max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('poblacion', 'Poblacion (Urban)'), ('rural', 'Rural')], default='poblacion', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g. "1949", "1950s", or "Present"', max_length=30)),
                ('description', models.TextField()),
                ('is_present', models.BooleanField(default=False, help_text='Styles this entry as the gold "Present" marker instead of a year.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
