# Generated by Django 6.0.6 on 2026-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_seed_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='super_admin_photos/'),
        ),
    ]
