# Generated by Django 6.0.6 on 2026-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0015_default_emergency_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='ticker_interval_seconds',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
