# Generated by Django 6.0.6 on 2026-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_sitecontactinfo_ticker_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='map_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontactinfo',
            name='map_place_name',
            field=models.CharField(blank=True, default='Municipal Hall of Tunga', max_length=120),
        ),
    ]
