# Generated by Django 6.0.6 on 2026-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_sitecontactinfo_map_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='news_slider_seconds',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
