# Generated by Django 6.0.6 on 2026-10-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_sitecontactinfo_news_slider_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='history_more',
            field=models.TextField(blank=True, help_text='Extra history text shown under the timeline.'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='history_more_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
