# Generated by Django 6.0.6 on 2026-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0020_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=True)),
                ('keep_count', models.PositiveIntegerField(default=14)),
                ('auto_include_files', models.BooleanField(default=True)),
                ('restore_status', models.CharField(blank=True, max_length=20)),
                ('restore_message', models.TextField(blank=True)),
                ('restore_started_at', models.DateTimeField(blank=True, null=True)),
                ('restore_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('safety', 'Safety (before restore)'), ('uploaded', 'Uploaded')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', 'In progress'), ('success', 'Complete'), ('failed', 'Failed')], default='running', max_length=20)),
                ('include_files', models.BooleanField(default=True)),
                ('size', models.BigIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
