# Generated by Django 6.0.6 on 2026-09-02 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0002_seed_offices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='offices.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_rep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
