# Generated by Django 6.0.6 on 2026-09-04 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('draft', 'Draft'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='office_dashboard.officerepresentative')),
            ],
        ),
    ]
