# Generated by Django 6.0.6 on 2026-09-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0002_announcement'),
        ('offices', '0002_seed_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerepresentative',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='offices.office'),
        ),
    ]
