# Generated by Django 6.0.6 on 2026-09-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0004_newsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('draft', 'Draft'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
