# Generated by Django 6.0.6 on 2026-09-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
