# Generated by Django 6.0.6 on 2026-09-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0007_alter_announcement_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
