# Generated by Django 6.0.6 on 2026-09-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0008_alter_newsupdate_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
