# Generated by Django 6.0.6 on 2026-09-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0010_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerepresentative',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
