# Generated by Django 6.0.6 on 2026-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0011_officerepresentative_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerepresentative',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rep_photos/'),
        ),
    ]
