# Generated by Django 6.0.6 on 2026-09-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0013_album_photo_album'),
        ('offices', '0003_office_about_office_description_office_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('permits', 'Permits & Licensing'), ('certificates', 'Certificates & Documents'), ('registration', 'Registration'), ('assistance', 'Public Assistance'), ('complaints', 'Complaints & Inquiries'), ('appointments', 'Appointments'), ('financial', 'Financial Services'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(choices=[('fa-solid fa-file-signature', 'Document / Signature'), ('fa-solid fa-id-card', 'ID Card'), ('fa-solid fa-hands-holding-circle', 'Public Assistance'), ('fa-solid fa-comments', 'Complaints / Inquiries'), ('fa-solid fa-star', 'Special Requests'), ('fa-solid fa-bullhorn', 'Proclamations / Announcements'), ('fa-regular fa-calendar-check', 'Appointments'), ('fa-solid fa-briefcase', 'Business / Permits'), ('fa-solid fa-house', 'Housing / Residency'), ('fa-solid fa-heart-pulse', 'Health Services'), ('fa-solid fa-graduation-cap', 'Education / Scholarship'), ('fa-solid fa-tree', 'Environment / Agriculture'), ('fa-solid fa-shield-halved', 'Peace & Order'), ('fa-solid fa-money-check-dollar', 'Financial / Treasury'), ('fa-solid fa-gavel', 'Legal Services')], default='fa-solid fa-file-signature', max_length=60)),
                ('availability', models.CharField(blank=True, max_length=150)),
                ('processing_time', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='offices.office')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
