# Generated by Django 6.0.6 on 2026-09-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0015_processstep'),
        ('offices', '0003_office_about_office_description_office_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='downloadable_forms/')),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadable_forms', to='offices.office')),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
