# Generated by Django 6.0.6 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0016_downloadableform'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadableform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
