# Generated by Django 6.0.6 on 2026-09-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('content', 'Content'), ('account', 'Account'), ('security', 'Security')], default='content', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-circle-info', max_length=50)),
                ('icon_color', models.CharField(default='var(--blue-600)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='office_dashboard.officerepresentative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
