# Generated by Django 6.0.6 on 2026-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0021_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadableform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
    ]
