# Generated by Django 6.0.6 on 2026-09-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0022_alter_announcement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('reject', 'Reject'), ('returned', 'Returned'), ('archive', 'Archived')], default='pending', max_length=20),
        ),
    ]
