# Generated by Django 6.0.6 on 2026-09-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0024_announcement_admin_note_downloadableform_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadableform',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloadable_forms', to='office_dashboard.service'),
        ),
    ]
