# Generated by Django 6.0.6 on 2026-09-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0025_downloadableform_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableform',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='office_dashboard.service'),
        ),
    ]
