# Generated by Django 6.0.6 on 2026-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0026_alter_downloadableform_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reminders',
            field=models.TextField(blank=True),
        ),
    ]
