# Generated by Django 6.0.6 on 2026-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0029_formfield_formsubmission_formsubmissionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='division',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='who_may_avail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
