# Generated by Django 6.0.6 on 2026-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0030_service_classification_service_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_scope',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=10),
        ),
    ]
