# Generated by Django 6.0.6 on 2026-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0031_service_service_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['transaction_number', 'order', 'created_at']},
        ),
        migrations.AddField(
            model_name='requirement',
            name='transaction_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='where_to_secure',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
