# Generated by Django 6.0.6 on 2026-09-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0032_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='agency_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='fee',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='processstep',
            name='person_responsible',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='processstep',
            name='processing_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
