# Generated by Django 6.0.6 on 2026-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0033_processstep_agency_action_processstep_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='processing_time_minutes',
        ),
        migrations.AddField(
            model_name='processstep',
            name='processing_time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='title',
            field=models.TextField(),
        ),
    ]
