# Generated by Django 6.0.6 on 2026-09-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0034_remove_processstep_processing_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='legal_basis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_of_service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
