# Generated by Django 6.0.6 on 2026-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0035_service_legal_basis_service_schedule_of_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['transaction_type', 'order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='requirement',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
