# Generated by Django 6.0.6 on 2026-09-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0036_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='edit_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
