# Generated by Django 6.0.6 on 2026-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0037_service_edit_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editing_enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Edit Settings',
                'verbose_name_plural': 'Service Edit Settings',
            },
        ),
    ]
