# Generated by Django 6.0.6 on 2026-09-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0038_serviceeditsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='edit_enabled',
        ),
    ]
