# Generated by Django 6.0.6 on 2026-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0039_remove_service_edit_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Display order on the office's public page. Lower numbers show first."),
        ),
    ]
