# Generated by Django 6.0.6 on 2026-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0045_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formfield',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formfield',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='formfield',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='formfield',
            name='uppercase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formfield',
            name='v_align',
            field=models.CharField(choices=[('bottom', 'Bottom'), ('middle', 'Middle'), ('top', 'Top')], default='bottom', max_length=10),
        ),
    ]
