# Generated by Django 6.0.6 on 2026-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0046_formfield_bold_formfield_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='fee',
            field=models.TextField(blank=True),
        ),
    ]
