# Generated by Django 6.0.6 on 2026-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0047_service_approved_at_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerepresentative',
            name='last_weekly_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerepresentative',
            name='notify_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officerepresentative',
            name='notify_approvals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officerepresentative',
            name='notify_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officerepresentative',
            name='notify_weekly_summary',
            field=models.BooleanField(default=False),
        ),
    ]
