# Generated by Django 6.0.6 on 2026-10-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0048_officerepresentative_last_weekly_summary_at_and_more'),
        ('offices', '0013_office_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChartNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Person'), ('section', 'Section / Unit')], default='person', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='org_chart/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_nodes', to='offices.office')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='office_dashboard.orgchartnode')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
