# Generated by Django 6.0.6 on 2026-10-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0049_orgchartnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgchartnode',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgchartnode',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
