# Generated by Django 6.0.6 on 2026-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0050_orgchartnode_pos_x_orgchartnode_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgchartnode',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
