# Generated by Django 6.0.6 on 2026-10-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_dashboard', '0051_orgchartnode_style'),
        ('offices', '0013_office_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_office_page', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_settings', to='offices.office')),
            ],
        ),
    ]
