# Generated by Django 6.1.1 on 2026-10-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office_dashboard", "0052_orgchartsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="content_photos/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_photos",
                        to="office_dashboard.announcement",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_photos",
                        to="office_dashboard.event",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_photos",
                        to="office_dashboard.newsupdate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]