# Generated by Django 6.0.6 on 2026-09-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_seed_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='office',
            name='head_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='office_logos/'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='position_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
