# Generated by Django 6.0.6 on 2026-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_office_about_office_description_office_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
