# Generated by Django 6.0.6 on 2026-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="slug",
            field=models.SlugField(unique=True, max_length=150),
        ),
    ]