# Generated by Django 6.0.6 on 2026-09-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_office_about_office_description_office_email_and_more'),
        ('offices', '0005_rename_offices'),
    ]

    operations = [
    ]
