# Generated by Django 6.0.6 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_office_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='mandate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='service_pledge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
