# Generated by Django 6.0.6 on 2026-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0009_office_goal_office_mandate_office_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Banner image shown at the top of this office's public page. Defaults to the standard municipal hall photo when empty.", null=True, upload_to='office_hero/'),
        ),
    ]
