# Generated by Django 6.0.6 on 2026-09-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_office_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Link to this office's official Facebook page, shown as an icon on its public page."),
        ),
    ]
