# Generated by Django 6.0.6 on 2026-09-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0011_office_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Link to this office's official Instagram page, shown as an icon on its public page."),
        ),
        migrations.AddField(
            model_name='office',
            name='twitter_url',
            field=models.URLField(blank=True, help_text="Link to this office's official X (Twitter) page, shown as an icon on its public page."),
        ),
        migrations.AddField(
            model_name='office',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="Link to this office's official YouTube channel, shown as an icon on its public page."),
        ),
    ]
