# Generated by Django 6.0.6 on 2026-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0012_office_instagram_url_office_twitter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='display_order',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
