# Generated by Django 6.0.6 on 2026-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0013_office_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='youtube_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
